name:                tetris-hs
version:             0.1.0.0
github:              "S3NP41-v/tetris-hs"
license:             MIT
author:              "S3NP41"
maintainer:          "S3NP41v@gmail.com"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/tetris-hs#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
# - -optl-mwindows
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - GLUT
  - time
  - random

executables:
  tetris-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tetris-hs
    - GLUT
    - time
    - random
